version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: spus_db
    environment:
      POSTGRES_USER: spus
      POSTGRES_PASSWORD: uUasYhasE
      POSTGRES_DB: spus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
